---
name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: "3.12"

      - name: Install the project
        run: uv sync --locked

      - name: Run tests
        run: uv run pytest -v --junitxml=test-results.xml solutions/lab_refactoring
        # Using this lab as an example.

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results.xml
