---
name: mkdocs
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/docs.yaml"
  release:
    types: [published]
permissions:
  contents: write
jobs:
  deploy:
    name: deploy
    strategy:
      matrix:
        python-version: ["3.12"]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --group doc

      - name: Publish mkdocs to gh
        run: uv run mkdocs gh-deploy --force
